[2025-08-27 13:33:51,764] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:33:51] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:33:51,772] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:33:51] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:33:51,775] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:33:51] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:33:51,958] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:33:51] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:34:20,205] WARNING update_ativo() L128  Erro ao atualizar ativo 'NTB-00124', Ativo não encontrado na base. - call_trace=C:\Users\HV6586\Downloads\Faculdade\minha_api_puc\app.py L128 
[2025-08-27 13:34:20,221] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:34:20] "[33mPUT /ativo?tag_patrimonio=NTB-00124 HTTP/1.1[0m" 404 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:35:50,111] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:35:50] "POST /ativo HTTP/1.1" 200 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:36:06,565] WARNING add_ativo() L59   Erro ao adicionar ativo 'Notebook Dell Latitude 5450': Ativo com a mesma tag de patrimônio já salvo na base. - call_trace=C:\Users\HV6586\Downloads\Faculdade\minha_api_puc\app.py L59  
[2025-08-27 13:36:06,567] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:36:06] "[31m[1mPOST /ativo HTTP/1.1[0m" 409 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:36:21,144] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:36:21] "POST /ativo HTTP/1.1" 200 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:37:07,909] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:37:07] "PUT /ativo?tag_patrimonio=NTB-00124 HTTP/1.1" 200 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:53:56,428] INFO _log() L187  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.214.193.188:5000 - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:53:56,428] INFO _log() L187  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:00,763] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:00] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:00,797] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:00] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:01,264] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:01] "[36mGET /openapi/scalar/images/scalar.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:01,316] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:01] "[36mGET /openapi/rapipdf/images/rapipdf.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:01,316] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:01] "[36mGET /openapi/redoc/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:01,329] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:01] "[36mGET /openapi/rapidoc/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:01,334] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:01] "[36mGET /openapi/elements/images/elements.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:01,334] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:01] "[36mGET /openapi/swagger/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:03,667] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:03] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:03,732] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:03] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:03,737] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:03] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:03,738] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:03] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:03,856] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:03] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:30,052] ERROR log_exception() L1449 Exception on /ativo [POST] - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask_openapi3\scaffold.py", line 123, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\minha_api_puc\app.py", line 43, in add_ativo
    ativo = Ativo(
            ^^^^^^
TypeError: __init__() got an unexpected keyword argument 'status'
[2025-08-27 13:54:30,061] INFO _log() L187  127.0.0.1 - - [27/Aug/2025 13:54:30] "[35m[1mPOST /ativo HTTP/1.1[0m" 500 - - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\werkzeug\_internal.py L187 
[2025-08-27 13:54:53,983] ERROR log_exception() L1449 Exception on /ativo [POST] - call_trace=C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\.venv\Lib\site-packages\flask_openapi3\scaffold.py", line 123, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HV6586\Downloads\Faculdade\minha_api_puc\app.py", line 43, in add_ativo
    ativo = Ativo(
            ^^^^^^
TypeError: __init__() got an unexpected keyword argument 'status'
